repos:
  - hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.1.0
  - hooks:
      - args:
          - --profile
          - black
        id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.12.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 23.7.0
  - hooks:
      - entry: mypy
        id: mypy
        language: system
        name: mypy
        pass_filenames: false
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
  - hooks:
      - id: prettier
        types_or: [ini, json, toml, yaml, markdown]
        exclude: CHANGELOG.md
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
