LOG_PATH: climate_token/log/debug.log
DB_PATH: climate_explorer/db/climate_activity_CHALLENGE.sqlite
CLIMATE_EXPLORER_SERVER_HOST: 0.0.0.0
BLOCK_START: 1500000
BLOCK_RANGE: 10000
MIN_DEPTH: 4
CADT_API_SERVER_HOST: https://observer.climateactiondata.org/api
CADT_API_KEY:
CHIA_HOSTNAME: localhost
CHIA_FULL_NODE_HOSTNAME:
CHIA_FULL_NODE_RPC_PORT: 8555
CHIA_WALLET_HOSTNAME:
CHIA_WALLET_RPC_PORT: 9256
DEFAULT_FEE: 1000000000 # mojos
CLIMATE_TOKEN_REGISTRY_PORT: 31312
CLIMATE_EXPLORER_PORT: 31313
CLIMATE_TOKEN_CLIENT_PORT: 31314
DEV_PORT: 31999
SCAN_ALL_ORGANIZATIONS: false
