[tool.poetry]
name = "ivern-chialisp"
version = "0.1.0"
description = ""
authors = ["Harry Hsu <stmharry@hashgreen.net>"]

[tool.poetry.dependencies]
python = "^3.10"
chia-blockchain = { path = "./chia-blockchain", develop = true }
fastapi = "^0.83.0"
uvicorn = "^0.18.3"
SQLAlchemy = "^1.4.41"
requests = "^2.28.1"
fastapi-utils = "^0.2.1"
SQLAlchemy-Utils = "^0.38.3"
pydantic = { extras = ["dotenv"], version = "^1.10.2" }

[tool.poetry.dev-dependencies]
# has to be disabled unfortunately due to developing chia-blockchain
# chia-dev-tools = "^1.1.1"
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
commitizen = "^2.27.1"

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0"
tag_format = "v$version"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
