name: Create release notes

on:
  push:
    tags:
      - "**"
      - "!*-rc*"

permissions:
  contents: write

jobs:
  release-notes:
    name: Create release notes from changelog
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          # Need REPO_COMMIT token so when the tag is created, the tag automation runs
          token: ${{ secrets.REPO_COMMIT }}
          fetch-depth: 0

      # Install Python for commitizen, the automatic changelog tool
      - name: Setup Python
        uses: Chia-Network/actions/setup-python@main
        with:
          python-version: "3"

      - name: Install commitizen
        run: |
          pip install -U commitizen

      - name: Create incremental changelog
        run: |
          cz changelog $GITHUB_REF_NAME --file-name=INCREMENTAL.md

      - name: Create release with the Changelog as release notes
        uses: softprops/action-gh-release@v2
        with:
          body_path: INCREMENTAL.md
          token: ${{ secrets.REPO_COMMIT }}
