name: Build & Release

on:
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  check-version:
    name: Create release notes from changelog
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        uses: Chia-Network/actions/clean-workspace@main

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          # Need PACKAGE_ADMIN_PAT token so when the tag is created, the tag automation runs
          token: ${{ secrets.PACKAGE_ADMIN_PAT }}
          fetch-depth: 0

      - name: Create release with the Changelog as release notes
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.PACKAGE_ADMIN_PAT }}
