name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: Chia-Network/actions/setup-python@main
        with:
          python-version: '3.10'

      - name: Create virtual environment
        uses: Chia-Network/actions/create-venv@main
        id: create-venv

      - name: Activate virtual environment
        uses: Chia-Network/actions/activate-venv@main
        with:
          directories: ${{ steps.create-venv.outputs.activate-venv-directories }}

      - name: Run poetry install
        uses: Chia-Network/actions/poetry@main
        with:
          poetry-command: "install --with dev"

      - name: Run Python tests
        env:
          PYTHONPATH: "./chia-blockchain"
          MODE: dev
        run: python -m pytest -k "not TestActivities" tests
